### ISSUE TITLE
NoneType split error

### ISSUE THREAD

**Issue by RandallShanePhD** [RandallShanePhD/fkscore#1]
FIX THIS!!

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 3006, in wrapper
    return method(self, *args, **kwargs)
...
  File "/usr/local/lib/python3.5/dist-packages/fkscore/fkscore.py", line 22, in __init__
    self.basic_stats(text)
  File "/usr/local/lib/python3.5/dist-packages/fkscore/fkscore.py", line 27, in basic_stats
    words = [x for x in text.replace('-', ' ').split(' ') if x != '']
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by RandallShanePhD** [comment]
fixed
